### ISSUE TITLE
Mekan

### ISSUE THREAD

**Issue by delirehberi** [Webendorg/2018#1]
Mekan önerisinden önce şehir seçimi için twitter üzerindeki anket sonucu geçerli olacaktır.

[Anket](https://twitter.com/webendorg/status/922932840798523393)

**Comment by cagataycali** [comment]
Denizli de yapma imkanımız olabilir mi?

**Comment by delirehberi** [comment]
Bölge olarak yaklaştık aslında, fakat öneri olarak dursun denizli. Denizli de olmasını isteyenler buradan veya twitterdan oy verebilirler. Diğer oylarla karşılaştırılıp karar verilir.

**Comment by delirehberi** [comment]
Trabzon için twitter üzerinden 160 oy gelmiş durumda. Trabzone oy eklemek için bu yoruma tepki verebilirsiniz ( 👍 ve 👎 ler sayılacaktır)

**Comment by delirehberi** [comment]
Erzincan için twitter üzerinden 53 oy gelmiş durumda, Erzincan'a oy eklemek için bu yoruma tepki veerebilirsiniz. ( 👍  ve 👎 ler sayılacaktır )

**Comment by delirehberi** [comment]
Bursa için twitter üzerinden 86 oy gelmiş durumda, Bursa'ya oy eklemek için bu yoruma tepki veerebilirsiniz. ( 👍  ve 👎 ler sayılacaktır )

**Comment by delirehberi** [comment]
Antalya için twitter üzerinden 75 oy gelmiş durumda, Antalya'ya oy eklemek için bu yoruma tepki veerebilirsiniz. ( 👍  ve 👎 ler sayılacaktır )

**Comment by BTaskaya** [comment]
Sadece bu 4 şehir mi var ?

**Comment by delirehberi** [comment]
@BTaskaya hayır, şehir öneriniz varsa yorum olarak öneri sunabilirsiniz. Yoruma 👍 ve 👎 tepki vererek oylanabilir.

**Comment by BTaskaya** [comment]
Adana

**Comment by alpeer** [comment]
Ankara

**Comment by delirehberi** [comment]
Sonuçlara göre 2018 Webend Ankara'da yapılacaktır.

- Ankara 9
- Denizli 7 
- Trabzon 2
- Adana 1
- Bursa 1

**Comment by delirehberi** [comment]
Etkinlik Tobb Etü'de gerçekleştirilecektir.
