### ISSUE TITLE
Akşam Eğlencesi

### ISSUE THREAD

**Issue by delirehberi** [Webendorg/2018#13]
Mekan henüz net değil ancak Akşam Eğlencesi'ne katılmak için bilet zorunluğu bulunacak. Biletler için mekanlarla görüştükten sonra bir fiyat belirleyeceğiz.

**Comment by puskuruk** [comment]
June Pub'a ne dersiniz? Daha sakin ve networkinge uygun bir gece olabilir.
http://junepub.com.tr/
https://www.instagram.com/junecaz/

**Comment by ahmetkakici** [comment]
- Mekandan beklenti yemek mi yoksa kahve içip sohbet ederiz diye mi düşünüyorsunuz?
- TOBB'a yakın Arabica Coffe House var Koç Kule'de, mekan büyük ve ferah görünüyor ama yemek konusu sıkıntılı. 
- TOBB'dan geçen bir toplu taşıma seçeneği var mı bilmiyorum ama eğer varsa ona göre bir mekan belirlemek de iyi olabilir.

**Comment by delirehberi** [comment]
Yemek tercih ediyoruz, savaş sonrası aç ve yorgun olacaklar.

Tobb önünden kızılay, bahçeli 8 e dolmuş gidiyor.

Koç kulelere ulaşım taksi yahut yürüme ile mümkün, toplu ulaşım yok.

16 Nis 2018 Pzt, saat 21:28 tarihinde Ahmet Kakıcı <notifications@github.com>
şunu yazdı:

**Comment by delirehberi** [comment]
Zigana Pide'de gerçekleştirildi.
