### ISSUE TITLE
Konuşmacılar

### ISSUE THREAD

**Issue by delirehberi** [Webendorg/2018#2]
Bu issue altında önermek istediğiniz konuşmacıların İsim soyisim, twitter, github bağlantılarını paylaşabilirsiniz. Yazılan yorumları oylayarak hangi konuşmacıları istediğinizi belirtebilirsiniz. Sadece 👍 ve 👎 emojileri sayılacaktır. Kendiniz de öneri sunabilirsiniz.

**Comment by delirehberi** [comment]
@enobayram Haskell ile ilgili konuşmak üzere davet edilebilir.

**Comment by delirehberi** [comment]
@fatih davet edilebilir.

**Comment by delirehberi** [comment]
@ustun davet edilebilir

**Comment by delirehberi** [comment]
@rakyll davet edebiliriz

**Comment by delirehberi** [comment]
@berkerpeksag davet edilebilir.

**Comment by delirehberi** [comment]
@fehmicansaglam davet edilebilir.

**Comment by delirehberi** [comment]
@eserozvataf davet edilebilir

**Comment by alpeer** [comment]
@alpeer, konuşmacı olmak isterim :)

**Comment by enobayram** [comment]
@delirehberi davet için teşekkürler, tarih ve şehir belli olduktan sonra ancak kesin bir cevap verebilirim, ama katılmak isterim.

**Comment by delirehberi** [comment]
@BilgisayarKavramlari Sadi Evren Şeker  [youtube](https://www.youtube.com/channel/UCkkgrhDCJheXQNIFqUVw0_g)

**Comment by hmert** [comment]
@hikalkan ASP.NET Boilerplate - Application Framework https://www.aspnetboilerplate.com

**Comment by delirehberi** [comment]
Orkut Murat Yılmaz https://www.linkedin.com/in/orkutmuratyilmaz/

**Comment by delirehberi** [comment]
8 konuşmacı için davetiye epostaları gönderildi. Kesinleştiğinde buradan da paylaşacağım. Şimdilik başka öneri almıyoruz.
