### ISSUE TITLE
Konsept

### ISSUE THREAD

**Issue by delirehberi** [Webendorg/2018#4]
İlk etkinliğimizde "Bunca dil varken, neden bunca dil var?" sorusuna odaklanmıştık.
İkinci etkinliğimiz ise "Yazılımcı Hikayeleri"ne odaklandı.
Üçüncü ve son etkinliğimizde "Proje Hikayeleri" konusu işlendi.

---
Yorum olarak üç konsepti de yazacağım. Oylayabilirsiniz. Farklı bir konsept önerisi olanlar yine yorum olarak ekleyebilir. Sadece 👍 ve 👎 emojileri sayılacaktır.

**Comment by delirehberi** [comment]
Bunca dil varken, neden bunca dil var?

**Comment by delirehberi** [comment]
Yazılımcı Hikayeleri

**Comment by delirehberi** [comment]
Proje Hikayeleri

**Comment by hamzauzumcu** [comment]
Çok daha fazla kitleye hitap etmek istiyorsanız, etkinlik kayda alınmalı, etkinlikten sonra yayınlanmalı.

**Comment by alpeer** [comment]
Proje Hikayeleri👍🏼

**Comment by aliemre** [comment]
Büyük Ölçekli Uygulamaları Yönetmek

**Comment by delirehberi** [comment]
Açık kaynak
Bu etkinliği Açık kaynak projeleri hikayeleri gibi organize edebiliriz. Sadece açık kaynak proje geliştiren ve bunlara destek arayan, tanıtmak isteyen, övünmek isteyen, bu projeyi yaparken edindikleri tecrübeyi paylaşmak isteyenlerin konuşabileceği bir etkinlik olarak.

**Comment by hmert** [comment]
*startup deck*
projeleri dinledik, detaylarını da dinledik. Ürüne dönüştükten sonra ne oluyor ne operasyon oluyor bu seviyedeyken ne gibi tecrübeler edindiler bunları dinlemek güzel olurdu diye düşünüyorum.

**Comment by delirehberi** [comment]
"Bulut teknolojileri", amazon, gcloud, ibmbluemix, digital ocean gibi servislerin yoğun olarak kullanıldığı projeleri merkeze alan, bulut güzellemesi yapacağımız bir konsept düşünüyorum. @hmert 'in tavsiyesini de eklersek, konuşmaya konu olacak ürünlerin aktif pazarda yer alan projelerden seçilmesi güzel olabilir.

**Comment by delirehberi** [comment]
Konsept Açık Kaynak olarak belirlenmiştir. startup deck konusu çok fazla "girişimci" durabileceği için odağımız olan "Backend Teknolojileri ve yazılımcılar" dan çok fazla uzaklaşma istemiyoruz.
