### ISSUE TITLE
Süre

### ISSUE THREAD

**Issue by delirehberi** [Webendorg/2018#5]
Süre şimdiye kadar hep 1 tam gün olarak belirlenmişti. Ancak yorumlarla önerinizi sunabilir veya önerilere oy verebilirsiniz. 👍 ve 👎 emojileri sayılacaktır.

**Comment by eserozvataf** [comment]
Hackathlon olmadigi surece 1 gunun uygun oldugunu dusunuyorum.

**Comment by hdogan** [comment]
1 gun etkinlik + yarim gun atolye

**Comment by delirehberi** [comment]
@hdogan aynı gün içinde paralel olarak ilerletmek tarzında düşünmüştük, Bahçeşehirdeki gibi, sence ayrı günlerde mi yapmalı atölye ve etkinlikleri?

**Comment by hdogan** [comment]
@delirehberi bahcesehirdekine katilmadim, atolyeye katilanlar konusmalara katilmak istediler mi istemediler mi buna fikir donusu lazim esasinda. Fakat benim katildigim atolyeli etkinliklerde; etkinlik sonrasi aksama dogru oldugunda genelde bir yorgunluk/tembellik gozlemim oldu, dusunulunce ertesi gun yapildiginda da yine sadece atolye icin sayida/talepte/istekte azalma olabilir... Paralel oldugundaki duruma ait negatif bir gozlem yoksa en uygunu paralel gitmesi olur yine sanirim.

**Comment by delirehberi** [comment]
Tek gün paralel şeklinde o zaman. İtirazı olan olmazsa etkinlik mekanı kesinleştiğinde tarihi tek gün olarak ayarlar bu issue'yu kapatırız.

**Comment by delirehberi** [comment]
Biraz lite bir etkinlik gibi geçebilir bu yılki. Tek gün, tek salon olarak. En fazla 30 dakika süren konuşmalar şeklinde 9 konuşma planlıyorum.

**Comment by delirehberi** [comment]
Etkinlik 1 gün sürecek.
