### ISSUE TITLE
Atölyeler

### ISSUE THREAD

**Issue by delirehberi** [Webendorg/2018#6]
Yorum olarak yapılabilir atölyeleri ekleyeceğiz. Puanlayarak veya öneri sunarak katkı yapabilirsiniz. 👍 ve 👎 emojileri sayılacaktır.

**Comment by delirehberi** [comment]
Django atölyesi

**Comment by delirehberi** [comment]
Ruby atölyesi

**Comment by delirehberi** [comment]
Symfony atölyesi

**Comment by delirehberi** [comment]
Laravel atölyesi

**Comment by delirehberi** [comment]
ExpressJS atölyesi

**Comment by sarpdorukaslan** [comment]
VueJS Atölyesi

**Comment by hdogan** [comment]
.NET Core/Mono atolyesi

**Comment by alpeer** [comment]
Redis atölyesi

**Comment by berkaybeyaz1** [comment]
React Native atölyesi

**Comment by delirehberi** [comment]
Atölye için yer sıkıntımız var bu sebeple atölyeler iptal.
